image: git.motis-project.de:5001/motis/motis/build:latest

linux-release:
  tags:
    - docker
  script:
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
    - cmake-sccache-gcc-7 -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - ./pkg-test
    - sccache -s
  artifacts:
    paths:
      - build/pkg

windows-release:
  tags:
    - windows
  script:
    - git submodule update --init --recursive
    - set WD=%cd%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - cd %WD%
    - set BOOST_ROOT=C:\boost_1_70_0
    - mkdir build
    - cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel ..
    - ninja pkg pkg-test
    - pkg-test
  artifacts:
    paths:
      - build/pkg.exe
